# Generated by Django 5.2.4 on 2025-07-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_display_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_message', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_of_sale', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
